### ISSUE TITLE
TE: Error: verdict is Benign

### ISSUE THREAD

**Issue by dipenpatel235** [CheckPointSW/teapi#3]
python tp_api.py -R -fp /home/teapi/python/sample.pdf -fn sample.pdf -e xxx.xxx.xxx.xxx -p -r REPORTS/ --pdf 
[2019-03-12 09:48:32][INFO] Calculating hash of files 
[2019-03-12 09:48:32][INFO] Querying file: /home/teapi/python/sample.pdf 
[2019-03-12 09:48:34][INFO] PROGRESS:
[2019-03-12 09:48:34][INFO] Finished: 1 files
[2019-03-12 09:48:34][INFO] ----------- 1 Finished files -----------
[2019-03-12 09:48:34][INFO] Name: sample.pdf,	MD5: 4b41a3475132bd861b30a878e30aa56a,	SHA1: bfd009f500c057195ffde66fae64f92fa5f59b72
	TE: Error: verdict is Benign
return 0

**Comment by zoharme** [comment]
hi @dipenpatel235, I don't understand the problem
is this a malicious file you're testing?

**Comment by Tubbs10** [comment]
When you look at the reponse it's giving in debug mode (-d) it says that "verdict": "Benign". This does not match with teapi-master/python/utils/gs.py file that has BENIGN defined as benign (lower case first letter). So fixing this variable to have uppcase first letter for BENIGN and MALICIOUS fixed the issue for me. Not sure though if ERROR and MESSAGE has the same issue.

So my utils/gs.py now looks like this:
BENIGN = 'Benign'
MALICIOUS = 'Malicious'
ERROR = 'error'
MESSAGE = 'message'

and it works as expected. Now also malicious files gets proper severity and confidence values which does not happen if these are wrong.

The output you see comes from teapi-master/python/api/te.py from else statement as it does not match with if and elif statements before:

    def __str__(self):
        if self.verdict == utils.gs.BENIGN:
            return 'TE: Benign'
        elif self.verdict == utils.gs.MALICIOUS:
            return 'TE: Malicious, Severity: %d, Confidence: %d' % (
                self.severity, self.confidence)
        else:
            return 'TE: Error: %s' % self.status

I think this is a bug.

**Comment by chkp-shakedk** [comment]
We no longer support using this tool to access the local Threat Emulation appliance API.
To see instructions on how to upload files on the appliance, see - https://community.checkpoint.com/t5/SandBlast-Network/Best-Practices-for-Threat-Prevention-API-Calls-to-Appliance/td-p/82825
